version: "3.3"
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=masterkey


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin1234
      #- GF_USERS_ALLOW_SIGN_UP=false

  backend:
    ports:
      - "8080:8080"

  prometheus:
    ports:
      - "9090:9090"